### ISSUE TITLE
Log exception error

### ISSUE THREAD

**Issue by ahdzesq** [corentinaltepe/nlog.loki#60]
I've tried to log an exception, and after logging the exception an error has occurred

Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func'3 formatter, List'1& exceptions, TState& state)
   at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func'3 formatter)
   at NLog.Extensions.Logging.NLogLogger.CreateLogEventInfo[TState](LogLevel nLogLogLevel, EventId eventId, TState state, Exception exception, Func'3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(FormattedLogValues state, Exception error)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan'1 args)
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan'1 args)

there is any known issue about this, o some workaround?

the layout that I'm using is the following:

`
${longdate} --> [${level:uppercase=true}] [${logger}] ${message} ${exception:format=Message,StackTrace,Data:maxInnerExceptionLevel=10}
`

Thanks for helping!

**Comment by corentinaltepe** [comment]
Hi @ahdzesq. Thank you for reporting the issue. I've tried but could not reproduce the issue.
in branch `60-log-exception-error`, I've applied the same message layout as yours in the template console program and the exceptions are properly reported in Grafana Loki.

![image](https://user-images.githubusercontent.com/14869153/205845035-45d3d061-74a0-4e8b-83e8-6a5bbf6cda6a.png)

You should try to isolate the root issue of your problem. Here are some things you could try :
- log to console instead of Loki. Do you have the same issue ? If so, NLog.Targets.Loki is not your root cause, as it doesn't show in your stack trace.
- try updating Loki, NLog.Targets.Loki, NLog, etc.
- try a different message layout

**Comment by snakefoot** [comment]
If you read the error-message, then it says there says the log-event-message is invalid:
```
Input string was not in a correct format.
at System.Text.ValueStringBuilder.ThrowFormatInvalidString()
```
It is not a problem with NLog.Loki, but a problem in your application. The format-string being used is not supported by Microsoft Extension Logging-Framework.

**Comment by ahdzesq** [comment]
Hello guys, thanks for your reply

I've found the issue, it was a really nested log error that had an extra curly bracket like this: {AccountId}**}**

We can close the issue.

Regards!

**Comment by corentinaltepe** [comment]
Thank you for your feedback!
